selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/beststore
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: XulFdTA38JcM2J2OEp6u55YcVlT5Onya
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt